set cb=unnamedplus
set nu rnu
set ts=4 sts=4 sw=4 cr et sta
set udir=~/.vim/undodir udf ul=10000 ur=100000
set sb spr
set ai si
set hid noswf nowb
set ss=1 siso=3 so=2
set is nows ic scs
set noto ttimeout tm=0 ttm=0 ut=100
set bs=indent,eol,start
set fo=q shm=atIAcFW
set list lcs=tab:>\ ,trail:·,extends:>,precedes:<,nbsp:+
set lz
set tw=79 nowrap
set spf=~/.vim/spell/en.utf-8.add spl=en_gb
set fdm=indent fdls=999
set ls=2 ru nosm sc nocul
set fcs=stl:\ ,stlnc:\ ,vert:\|
ru macros/matchit.vim
set smc=200
set cot=menu,menuone,longest,preview
set wim=list:longest,full wic wcm=<C-z>
set path=,
set wig+=**/.git/**,**/__pycache__/**,**/venv/**,**/node_modules/**,*.pyc,tags
set viminfo='15,<50,s10,h
set go= mouse= gfn=consolas:h14
set vb noeb t_vb=
colo nord
set tgc background=dark
syntax enable
filetype plugin indent on

au CmdlineEnter [/\?] :set hlsearch
au CmdlineLeave [/\?] :set nohlsearch
au QuickFixCmdPost [^l]* cwindow
au QuickFixCmdPost l* lwindow
au VimEnter * cwindow

let g:netrw_bufsettings = 'noma nomod rnu nu nowrap ro nobl'
let &t_SI = '\e[6 q'
let &t_EI = '\e[2 q'
let &t_SR = '\e[4 q'
